version: "3"
services:
    web:
        image: nginx
        container_name: base-php-web
        depends_on:
            - app
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    app:
        container_name: base-php-app
        volumes:
            - ./src:/var/www/html
            - ./docker/app/php.ini:/usr/local/etc/php/php.ini
        build:
            context: ./
            dockerfile: ./docker/app/Dockerfile
